import { StyleSheet } from 'react-native';
const CARD_H = 230;

/* Styles */
const R = 14;

export const s = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#fff',
    // margin: 16,
    paddingBottom: 10,
    // height: '100%',
    borderRadius: R,
    padding: 12,
    gap: 10,
  },
  scrollContainer: {
    flex: 1,
    backgroundColor: '#fff',
    // margin: 16,
    // height: '100%',
    borderRadius: R,
    // padding: 12,
    gap: 10,
  },
  topBar: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 4,
    justifyContent: 'space-between',
  },
  story: {
    backgroundColor: '#07B007',
    padding: 10,
    borderRadius: 10,
    marginTop: 10,
  },
  dotsContainer: {
    position: 'absolute',
    bottom: 10,
    flexDirection: 'row',
    alignSelf: 'center',
    gap: 6,
  },
  dot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: 'rgba(255, 255, 255, 0.5)',
  },
  activeDot: {
    backgroundColor: '#07B007',
    width: 8,
  },
  whiteText: { color: '#fff', fontWeight: 500 },
  backIcon: { fontSize: 24, color: '#2A3B4C' },
  header: {
    marginTop: 20,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  sellerLeft: { flexDirection: 'row', alignItems: 'center' },
  avatarWrap: { position: 'relative' },
  avatar: { width: 42, height: 42, borderRadius: 21 },
  followBtn: {
    position: 'absolute',
    right: -2,
    bottom: -2,
    width: 18,
    height: 18,
    borderRadius: 9,
    backgroundColor: '#07B007',
    alignItems: 'center',
    justifyContent: 'center',
  },
  followPlus: { color: '#fff', fontSize: 12, fontWeight: '800' },
  sellerInfo: { marginLeft: 8 },
  sellerName: { fontSize: 14, fontWeight: '700', color: '#0B1C2E' },
  postedTime: { fontSize: 12, color: '#7A8A9D', marginTop: 2 },
  sellerType: {
    backgroundColor: '#F1F5F9',
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 5,
  },
  sellerTypeText: { fontSize: 12, color: '#2C4A6B', fontWeight: '600' },

  carouselWrap: { marginTop: 6, borderRadius: R, overflow: 'hidden' },
  mainImage: { width: '100%', height: CARD_H, justifyContent: 'flex-end' },
  mainImageRadius: { borderRadius: R },

  thumbRow: { flexDirection: 'row', gap: 8, marginTop: 8 },
  thumb: { flex: 1, height: 68, borderRadius: 10, overflow: 'hidden' },
  thumbRadius: { borderRadius: 10 },
  overlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(0,0,0,0.45)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  overlayText: { color: '#fff', fontWeight: '700' },
  posted: { flexDirection: 'column', alignItems: 'center', gap: 4 },
  title: { fontSize: 16, fontWeight: '800', color: '#0B1C2E', marginTop: 6 },
  row: { flexDirection: 'row', alignItems: 'center', marginTop: 10 },
  icon: { marginRight: 4 },
  location: { fontSize: 12, color: '#667B8C' },

  statsRow: {
    flexDirection: 'row',
    gap: 16,
    alignItems: 'center',
    marginTop: 6,
  },
  stat: { flexDirection: 'row', alignItems: 'center' },
  statText: { color: '#667B8C', fontSize: 12, marginLeft: 2 },
  specBoxes: {
    flexDirection: 'row',
    gap: 8,
    marginTop: 10,
  },
  specBox: {
    // flex: 1,
    // aspectRatio: 1,
    width: '22.5%',
    height: 70,
    borderWidth: 1,
    borderColor: '#E6ECF2',
    padding: 10,
    borderRadius: 10,
    backgroundColor: '#FBFDFF',
    justifyContent: 'center',
    alignItems: 'center',
  },
  specValue: { fontWeight: '700', color: '#0B1C2E' },
  specLabel: { marginTop: 2, color: '#7A8A9D', fontSize: 11 },
  grid: {
    marginTop: 10,
    borderWidth: 1,
    borderColor: '#E6ECF2',
    borderRadius: 10,
    overflow: 'hidden',
    paddingVertical: 10,
  },
  gridRow: {
    flexDirection: 'row',
    // borderBottomWidth: StyleSheet.hairlineWidth,
    // borderBottomColor: '#E6ECF2',
  },
  gridItem: {
    flex: 1,
    paddingHorizontal: 12,
    paddingVertical: 10,
    // borderRightWidth: StyleSheet.hairlineWidth,
    // borderRightColor: '#E6ECF2',
  },
  gridLabel: { color: '#7A8A9D', fontSize: 12 },
  gridValue: { color: '#0B1C2E', fontWeight: '600', marginTop: 4 },

  sectionTitle: { marginTop: 12, fontWeight: '500', color: '#0B1C2E' },
  desc: { color: '#5B6D7C', marginTop: 6 },

  footer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: 12,
  },
  price: { color: '#07B007', fontSize: 20, fontWeight: '800' },
  perMonth: { color: '#7A8A9D', marginTop: 2, fontSize: 12 },
  actions: { flexDirection: 'row', gap: 8 },
  callActionBtn: {
    width: 42,
    height: 42,
    borderRadius: 10,
    backgroundColor: '#EFF6FF',
    alignItems: 'center',
    justifyContent: 'center',
  },
  messageActionBtn: {
    width: 42,
    height: 42,
    borderRadius: 10,
    backgroundColor: '#E9F7EA',
    alignItems: 'center',
    justifyContent: 'center',
  },
  NotiActionBtn: {
    width: 42,
    height: 42,
    borderRadius: 10,
    backgroundColor: '#FEF2F2',
    alignItems: 'center',
    justifyContent: 'center',
  },
  actionIcon: { fontSize: 18, color: '#07B007' },
});
